### ISSUE TITLE
Ignore browserify transform modules in --unused?

### ISSUE THREAD

**Issue by gsf** [maxogden/dependency-check#10]
It would be nice to be able to ignore browserify transform modules included in dependencies when calling dependency-check with `--unused`. Not sure what would be the best way to do it, though. Ideas so far:

1. An `--ignore` flag that could be used multiple times to specify each module. It could be useful in some cases on the `--missing` side as well.
2. Inspect the `browserify.transform` list in package.json as a source for ignores. I don't usually include that in the package.json for my applications (only in modules), but it should do no harm there.

**Comment by voxpelli** [comment]
Added a PR for option 1: https://github.com/maxogden/dependency-check/pull/23

**Comment by voxpelli** [comment]
An `--ignore` flag has been released over a year ago, but missed to reconnect here.

I will close this as solved as it is now possible to ignore browserify transform modules.

Any additional browserify specific features are probably best dealt with as new issues if someone still feel that they are needed.
