### ISSUE TITLE
Not getting extension to kick in

### ISSUE THREAD

**Issue by fatso83** [maxogden/dependency-check#102]
I just tried changing the name of my entry point from app.js to app.ts, and after that I just get `Detective function missing for "/home/dev/myproj/src/app.ts"`, which is weird, given that I have added an extension for handling that:

```diff
dependency-check package.json --no-dev --unused \
-    --entry src/app.js \
-    --extensions 'js,jsx:detective-es6' \
+    --entry src/app.ts \
+    --extensions 'js,jsx:detective-es6,ts:detective-typescript' \
```

The detective plugin for typescript seems to work, as it spits out the dependencies just fine when invoked on its own, which makes me suspect this is about something else:

```javascript
const fs = require('fs');
let detective = require('detective-typescript');

let mySourceCode = fs.readFileSync('src/app.ts', 'utf8');

// Pass in a file's content or an AST
let dependencies = detective(mySourceCode);
console.log(dependencies);
```

```
$ node foo.js 
[ 'moment/locale/nb',
  'moment',
  'react',
  'react-dom',
  './appinfo',
  './components/AppWrapper',
  './features/appStore',
  './features/buildinfo/buildinfo-actions',
  './integration',
  './lib/logging/Logger',
  './lib/service/ImageService' ]
```

This was all working fine with JSX, using the old config, so I was a bit surprised when getting this error, as it's almost the same.

**Comment by blakeembrey** [comment]
@fatso83 Try `--extensions 'js,jsx:detective-es6' --extensions 'ts:detective-typescript'`.

**Comment by fatso83** [comment]
That was it! Thank you.
