### ISSUE TITLE
Remove unused deps from package.json

### ISSUE THREAD

**Issue by RichardLitt** [maxogden/dependency-check#18]
Unless there's already a command for this in npm I am missing?

**Comment by maxogden** [comment]
hmm good question, I dunno how to do that

**Comment by RichardLitt** [comment]
Cool. I'll look into it, I'll see how `i --save` adds a line.

**Comment by RichardLitt** [comment]
Eh. Looks like this would be the only write command for this tool. Maybe not such a good idea, here, and this should just be a PR for npm?

**Comment by RichardLitt** [comment]
Yeah, actually, you can do this with just `npm uninstall kitty --save`. We could make a tool that automatically pipes the output of `check.extras` to a bash command, but it's probably better to do this manually.
