### ISSUE TITLE
Look for package.json in current dir if not provided as argument

### ISSUE THREAD

**Issue by RichardLitt** [maxogden/dependency-check#19]

**Comment by RichardLitt** [comment]
Happy to PR this if it sounds like a good idea.

**Comment by voxpelli** [comment]
Currently the help is printed when running just `dependency-check`, which in turn makes it easy to discover that you can write eg. `dependency-check .` to check the dependencies of the current directory.

Making the help so easily discoverable seems more beneficial to me than getting rid of the additional ` .` it takes to check the current directory. What do you think?

**Comment by RichardLitt** [comment]
Ah. I didn't realize I could just do `.`. That makes sense.
