### ISSUE TITLE
expand e.g. './index' to './index.js' and './index.json'

### ISSUE THREAD

**Issue by maxogden** [maxogden/dependency-check#26]
this is what `require` does, but https://www.npmjs.com/package/detective does not support it at the moment

**Comment by evilpacket** [comment]
It seems to me we wouldn't want to expand out to .json as detective / acorn would not care much about these to find requires in and that it would blow up on it, just the same as it does for .coffee files.

Would we want to ignore .coffee for now or parse those too?

**Comment by maxogden** [comment]
i'm happy supporting whatever node core supports. would be nice if this supported `.json` specifically because node core supports it, and I think it's the only thing that this doesn't support that node core does

**Comment by watson** [comment]
@maxogden I often `var pkg = require('./package')` to access for instance the current version etc. That doesn't work with this module. Should the functionality be added to this module or to detective?

**Comment by voxpelli** [comment]
@watson In case it's unclear – it does work if you change it to `var pkg = require('./package.json')`, that's what I do when I have the same use case as you – I actually think it's clearer overall.

**Comment by watson** [comment]
@voxpelli thanks, I know it's a workaround, but it would be nice if this module supported the same standard as Node.js so people didn't have to do this

**Comment by maxogden** [comment]
if you fix detective it will fix this module

**Comment by watson** [comment]
@maxogden I just took a look at detective and it doesn't seem to resolve the require argument at all.

E.g. given this source code:

```js
require('./')
require('./index')
require('./index.js')
```

I get the following result out of detective:

```js
[ './', './index', './index.js' ]
```

Are you sure this functionality doesn't belong in this module? Or maybe I'm missing something?

I'd be happy to add it either way of course 😃

**Comment by blakeembrey** [comment]
Seems like what we'd rather want to do is support multiple extension resolution in the project. Something like `-e js:precinct -e ts:typescript -e json:x` where `js`, `node` and `json` are all pre-loaded (since they are provided by node by default). For the start, we could add `json` and `node`, with `js` falling back into `detective` and allow each of these to be overridden. Basically merging the default map with the object map, and that should replicate node require resolution behaviour.
