### ISSUE TITLE
"Object.keys called on non-object" error  node -v 0.12.4 win32

### ISSUE THREAD

**Issue by jonovate** [maxogden/dependency-check#30]
Getting this on on package.json now, including dependency-check/package.json.

Object.keys(deps).forEach(function (dep) {
             ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at c:\Users\Jonathon J. Howey\AppData\Roaming\npm\node_modules\dependency-ch
eck\index.js:101:14
    at Array.forEach (native)
    at c:\Users\Jonathon J. Howey\AppData\Roaming\npm\node_modules\dependency-ch
eck\index.js:100:13

**Comment by jonovate** [comment]
So the call to getDeps() is returning immediately because "file" is being passed in as an absolute path.  '"c:\Users\Jonathon J. Howey\AppData\Roaming\npm\node_modules\dependency-ch
eck\index.js"'
This seems to be on purpose though because of path.join on lines 65 and 70 is creating the paths[] array to be absolute paths.

IS_NOT_RELATIVE.test(file) <== returns true. 

So the workaround is I commented it out locally, but I still don't understand the IS_NOT_RELATIVE vs lines 65 and 70.  They seem to be conflicting.

**Comment by voxpelli** [comment]
From the description of the issues it sounds like it would be possible to solve this by replacing the regexp with a module that supports checking Windows paths as well – like: https://github.com/jonschlinkert/is-relative The current one wont detect Windows paths properly.

Would have trouble testing it though as I don't have good access to a Windows machine.

@jonovate If you could try and replace it and test it and make a PR then that would be helpful.
