### ISSUE TITLE
constructive criticism

### ISSUE THREAD

**Issue by ORESoftware** [maxogden/dependency-check#36]
I honestly really want this lib to work. it's a great idea and the community needs it. but currently it doesn't work. sorry if this sounds very critical but I am confused and I hope to both alleviate my confusion and possibly provide constructive criticism.

I don't believe this lib is implemented correctly. By default you are taking input one .js file and hoping to recurse through all its require statements - this won't work because you will never ever cover all the .js files in a project.

Instead:

Why don't you just look at package.json, store an array of the dependencies as strings, and then recurse through all .js files in all directories of the project and look at the require('x') statements and see if x is in package.json? Obviously, the default would be to ignore node_modules and you would allow the user of your lib an options to --ignore other directories.

You aren't doing what I just suggested. You are taking one input file and hoping that somehow you will reach all files in a Node.js project? That's wishful thinking at best and setting us all up to fail at worst.

I don't see how this library can ever be useful as is, unless the developer is excepted to list every file in their project as arguments to --entry.

Very confused by this lib.

**Comment by ORESoftware** [comment]
at the very least could you provide a --verbose option so that this lib would print out the path of every .js file it looked at?

**Comment by voxpelli** [comment]
For most projects, at least the smaller ones, the current behavior of specifying a few entry points work fine.

One can also already pair this library with some other mechanism for finding files. Eg. the included grunt task uses the file selection mechanism provided by grunt to select the high files to look for.

But – sounds like what you would want is glob support in '--entry' so one can write eg. '--entry=lib/**/*.js' to select all js-files in that folder and its subfolders? I wouldn't be opposed to the addition of that.

**Comment by maxogden** [comment]
@ORESoftware this is designed for node modules which have specific entry points. Sounds like you have other criteria that we don't cover. I suggest you write your own module that scratches your own itch.

**Comment by ORESoftware** [comment]
ok yeah I just wanted to make sure this lib didn't have what I need, thanks for responding, I think it's worthwhile to write my own appreciate the feedback

**Comment by maxogden** [comment]
@ORESoftware sounds good. the module is less than 200 lines, i'm sure you can figure out what it's doing and maybe come up with ideas for your own tool https://raw.githubusercontent.com/maxogden/dependency-check/master/index.js

**Comment by ORESoftware** [comment]
I wrote one real quick

https://www.npmjs.com/package/nodejs-dep-check

go to the root of any project you wish to check and run mine like so:

node node_modules/nodejs-dep-check/test/test1.js

it will cover everything in your project that ends with .js, .ts or .jsx that is Node.js/CommonJS

by default it will cover all your files except node_modules

it's not configured to work with devDependencies or core modules yet

should be easy to fine tune

**Comment by ORESoftware** [comment]
https://github.com/ORESoftware/nodejs-dep-check

**Comment by ORESoftware** [comment]
The community needs something 99.99% reliable. Currently this lib can give absolutely no guarantees that it will find every require().

Obviously with dynamic require's like so:

```javascript
var x = require(z+'x.js');
```

it's harder to do, if not impossible, but I think we can safely assume the module being required is both not a core library and unlikely to be a dependency in package.json.

but for everything but dynamic requires, this lib needs to work 100%, otherwise it's useless.

You can use my lib like so with Mocha

```javascript
describe('@test-dep-check', function () {

    var assert = require('assert');

    it('[test]', function (done) {

        var ndc = require('nodejs-dep-check');

        var result = ndc.start({
            verbose: true,
            ignorePaths: ['/node_modules/'],
            ignoreDirs: ['node_modules', 'test']
        });

        //assert(!(result instanceof Error)); //no need for assert just pass the result to done()

        done(result);

    });

});
```

it's guaranteed to hit every .js file in your project that you don't ignore. It is also implemented with a lot less code. It would be very helpful if you could try my lib and give feedback, thanks for your feedback in general.

you don't need to specify package.json or whatever - right now my module just assumes package.json dependencies and starts at the root of the app because it knows where the root is.

so put the above file in /test

and run

```
mocha test
```
