### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by js08** [maxogden/dependency-check#38]
Hi,

We have tested the dependency-check package with a sample todo react app, Can you tell me why this error happening.

dependency-check
----------------
D:\todomvc\node_modules\.bin>dependency-check ..\..\package.json --unused
Fail! Modules in package.json not used in code: classnames, react, react-redux, redux, babel-core, babel-loader, expect, jsdom, mocha, mocha-jsdom, no
de-libs-browser, raw-loader, react-hot-loader, style-loader, todomvc-app-css, webpack, webpack-dev-server

**Comment by maxogden** [comment]
You have to specify the entry points you want to test https://github.com/maxogden/dependency-check#how-it-works

**Comment by voxpelli** [comment]
As there has been no response on this support request for almost a year, I'm going to close this for now. Please feel free to respond anyway and we can reopen it, or open a new issue if there's still some issue to be dealt with.

**Comment by js08** [comment]
@voxpelli did you test it??

**Comment by voxpelli** [comment]
@js08 It is possible to use dependency-check with React and JSX now, if specifying it to use a special parser. I'm doing it myself daily.

Using the `detective-cjs` parser one runs it like:

```
dependency-check . -e js,jsx --detective detective-cjs
```

Does that work for you?

**Comment by alkafaiz** [comment]
hey @js08  I have tried with your solution. still getting error
```
$ dependency-check . -e js,jsx --detective detective-cjs
No entry paths found
```
my project is bootstrapped with create-react-app. any other solutions?

**Comment by voxpelli** [comment]
@alkafaiz Ensure that you point it to the files you want to include in the checks, rather than just the dot. Eg: `dependency-check 'lib/**/*.jsx'`
