### ISSUE TITLE
not going to pull any punches here...

### ISSUE THREAD

**Issue by ORESoftware** [maxogden/dependency-check#41]
This has been a long time coming

sorry, I don't mean to be rude, but this library is going to fail a lot of people. I created a repo on Github that shows how this library fails, but let me give you a simple inline example of how and where it will fail:

```js
//A.js
var EE = require('events').EventEmitter;

var ee = new EE();

module.exports  = ee;
```

now we have

```js
//B.js
var ee = require('./A.js');
```

```js
//C.js
var ee = require('./A.js');
```

in package.json, if we have B or C as our value for "main" -
what will happen is that B or C will be seen by this library, but not both files, which means that this library will simple miss things that it should capture...

you KNOW this will fail, and this is for a small extremely simple project with 3 files. Imagine a large complex project, this will completely flop.

I highly recommend a cease and desist here and some sort of recognition of the shortcomings of this module

I created a library that solves the problem that this library wants to solve, but simply cannot as it is designed.

the following simple repo demonstrates the shortcomings of this module and how the nodejs-dep-check module works better:

https://github.com/ORESoftware/ndc-example-usage

my library is not perfect in terms of the formatting of the output, but it would be better for the Node.js community to have something that really works reliably

You can see from this screenshot, that this whole thing is a major fail:

![Nothing works](https://cloud.githubusercontent.com/assets/11139560/11707534/9d998882-9eba-11e5-94d4-59bb6d5053b8.png)

This module either missing everything completely by indicating success when it really shouldn't, or it only catches one missing module reference and not both

**Comment by maxogden** [comment]
@ORESoftware thanks for the feedback, if anyone has issues with this library I'll suggest they check yours out
