### ISSUE TITLE
Error with `graceful-fs`?

### ISSUE THREAD

**Issue by rafaelrinaldi** [maxogden/dependency-check#47]
Just installed `dependency-check` in a fresh new project and I'm getting the following error:

``` sh
$ dependency-check .

(node:3880) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
No entry paths found
```

Full log [here](https://gist.github.com/rafaelrinaldi/dd76b962e2998e983152925b8e083664).

My environment information:

``` sh
$ node -v
v6.2.2

$ npm -v
3.10.2
```

**Comment by voxpelli** [comment]
Can you try again now with the new `2.5.2` version and see if the dependency update made in #48 fixes the issue for you?

**Comment by voxpelli** [comment]
As there's been no update on this in either direction I'll assume that the dependency update worked
