### ISSUE TITLE
Option to error on require-call to dev dependency?

### ISSUE THREAD

**Issue by rexxars** [maxogden/dependency-check#53]
Maybe I'm missing something here. Let's say I have a node app. I'm running CI tests on Travis that includes running `dependency-check`, everything passes.

I deploy to production, where the deploy process runs `npm install --production`, skipping dev dependencies. The server crashes because I'm requiring a module only listed in `devDependencies`.

Would it make sense to have a flag I could provide that checks whether all the require statements from the entry point and onwards are listed in `dependencies`? Perhaps we could reuse `--no-dev`?

**Comment by gr2m** [comment]
I had the very same problem today (and many times in the past). I hacked together a little gist before I found dependency-check: https://gist.github.com/gr2m/b89a2cf0b36199f950189920bb824d24

@maxogden do you think what @rexxars suggests would be possible? Would you accept a PR for it?
