### ISSUE TITLE
[ERROR] No documents exist

### ISSUE THREAD

**Issue by hktalent** [maxogden/dependency-check#56]
os： mac os X 10.12.1

$ dependency-check --project Testing --out . --scan /Volumes/MyWork/MyWork/JY15MD002SK/04.Implement/lib
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
[INFO] Checking for updates
[ERROR] IO Exception: Connection reset
[ERROR] IO Exception: Connection reset
[WARN] Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[WARN] Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] No documents exist

Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Unable to download the NVD CVE data.
[ERROR] No documents exist

**Comment by blakeembrey** [comment]
I believe you're looking for https://github.com/jeremylong/dependencycheck.

**Comment by hktalent** [comment]
@blakeembrey  i use jdk8, so is ok
