### ISSUE TITLE
Support `/// <reference types`

### ISSUE THREAD

**Issue by unional** [maxogden/dependency-check#57]
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

If we use the typings, we are putting it in the `dependencies` and use `/// <reference types="<package>" />`.

`dependency-check` currently do not detect this is proper usage. 🌷 

EDIT: in order to do this, we need to check `*.d.ts`. `/// <reference types="..."/>` live in `*.d.ts` after compilation.

**Comment by blakeembrey** [comment]
Noted in https://github.com/maxogden/dependency-check/issues/59#issuecomment-275460827, this module would probably need to adopt some sort of plugin approach to make this work. Another approach would be TypeScript as a separate module or TSLint rules (TSLint rules might make the most sense).

**Comment by blakeembrey** [comment]
Closing in reference to https://github.com/maxogden/dependency-check/issues/59
