### ISSUE TITLE
why should peerDependencies checked?

### ISSUE THREAD

**Issue by unional** [maxogden/dependency-check#58]
I'm using `dependency-check` like this: 

`dependency-check . --unused --no-dev && dependency-check . --missing --no-dev`

With 2.7.0 it is checking peerDeps and fail.

In the comment of:
https://github.com/maxogden/dependency-check/commit/72b46c4a77847c08962e58383fe3a68942f6dd40

It seems like the change would let `--extra` to check peerDevs too.

But it seems like it is done for `--missing`?

IMO it should not be checked because the peerDeps describes what's needed when using the package, instead of what's being used by the package.

In my case, I'm writing in TypeScript and all it does is importing and augmenting the dependency's typings. Similar to `redux-thunk` vs `redux`.

The produced `.js` file does not have any usage of the peerDeps because it does not directly call it.

**Comment by blakeembrey** [comment]
@unional A peer dependency implies what is needed by the package for it to work. Most of the time, this would imply that it's being used but that your specific version requirements are more lenient and can be shared (e.g. a plugin ecosystem). Therefore, checking it would be the correct course of action and if it's not actually used explicitly, you should ignore it explicitly.

> But it seems like it is done for `--missing`?

This is how it should have worked before that commit already. See https://github.com/maxogden/dependency-check/commit/72b46c4a77847c08962e58383fe3a68942f6dd40#diff-168726dbe96b3ce427e7fedce31bb0bcL27 which only moved the location of that check and hasn't actually changed it (except that it allows the `--no-dev` option now).

**Comment by unional** [comment]
Ok. Thanks, Blake.
