### ISSUE TITLE
Drop support for < Node 4

### ISSUE THREAD

**Issue by voxpelli** [maxogden/dependency-check#62]
With reference to the test failure in #61: https://travis-ci.org/maxogden/dependency-check/jobs/196024596

Being able to use such simple things as `Object.assign()` makes for much simpler code. Isn't it time to stop supporting the older versions soon to enable that?

**Comment by blakeembrey** [comment]
I don't think there's any reason to upgrade prematurely. It might be worth keeping track of for a next major release.

**Comment by voxpelli** [comment]
As the failing tests in #79 showed, recently `dependency-check` stopped working on version older than Node 4 as `read-package-json` broke compatibility on one of their patch versions: https://github.com/npm/read-package-json/pull/72

This has shown in other projects as well: https://github.com/request/request/issues/2772#issuecomment-330879495

So question is how long we can actually claim to support those versions. We should probably move ahead and drop at least Node 4 pretty soon.

I would even go as far as to say that now we should aim for Node 6 and above as Node 4 ends LTS in April so everyone should be moving away from it now anyways. Node 6 should be the oldest Node-version any actively maintained project is using right now and older projects can always use the `1.x` branch

**Comment by voxpelli** [comment]
I would suggest we target Node 6 in `3.0.0` as Node 4 reaches end of life in three months – do you agree @blakeembrey?

**Comment by blakeembrey** [comment]
SGTM.

**Comment by voxpelli** [comment]
Fixed by: https://github.com/maxogden/dependency-check/commit/d0efa7051fcb9880bb931a17a7ebdf2879a62329
