### ISSUE TITLE
Ignore local node_modules

### ISSUE THREAD

**Issue by julien-f** [maxogden/dependency-check#63]
Hi,

I have specific global modules that I want to keep in my project but I want to require without having to use the relative path.

(I don't want to publish them as external packages because they are really specific, I want to keep them inside my project and it requires too much boilerplate −package.json, Babel config, etc.)

Currently `dependency-check` mark those modules as missing, is there a way to automatically mark them (like --search-in `dist/node_modules`)?

**Comment by blakeembrey** [comment]
Could you use the `--ignore` option to ignore the module(s) you want? This project doesn't actually look into `node_modules`, it only looks at the `package.json` definition.

**Comment by julien-f** [comment]
Not the perfect work-around for me (as I have to update the command line each time I create a new module), but I understand that this is out of dependency-check's scope.

Thanks for the answer!

**Comment by blakeembrey** [comment]
Hopefully we can come up with a way to support it in the near future. Something like a custom "dependency list" plugin like we are now doing with detective. I know that's needed for JSPM, so this might be another valid use-case.
