### ISSUE TITLE
Enable wildcards/minimatch for "ignore"

### ISSUE THREAD

**Issue by blakeembrey** [maxogden/dependency-check#65]
This would be useful in the case where NPM `@types/*` is used with TypeScript, for instance. Interested if there's counter arguments, but in general it seems to make it easier.

**Comment by tunnckoCore** [comment]
I think `micromatch` is better and battle-tested option. It seems and really is a lot faster. Not only that, but follows Bash spec in 99% and is compliant.

I can make a PR, it's easy really.

**Comment by tunnckoCore** [comment]
Btw, implemented it, i'll PR in a bit. Micromatch lots simplified both `.missing` and `.extra` functions, plus full support for ignores

**Comment by tunnckoCore** [comment]
<3
