### ISSUE TITLE
Unknown "Fail! Modules in package.json not used in code: coveralls" error

### ISSUE THREAD

**Issue by unional** [maxogden/dependency-check#69]
I have a repo currently failed to build due to error reported by `dependency-check`:

`dependency-check . --unused --no-dev && dependency-check . --missing --no-dev`:

https://travis-ci.org/unional/aurelia-logging-memory/builds/238300120?utm_source=github_status&utm_medium=notification

But I don't have `coveralls` listed in the package.json:
https://github.com/unional/aurelia-logging-memory/blob/master/package.json#L71-L92

Would it be some error related to node 8?

I can't reproduce this locally.

**Comment by blakeembrey** [comment]
@unional Yes, it's related to npm v5. `npm install coveralls` now adds it to `package.json` by default, you'd need to specify `--no-save` to invert the behaviour. I'd recommend either running the install command _after_ you do dependency check, or adding `--no-save`. See https://docs.npmjs.com/cli/install for updated docs on npm 5.
