### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by strugee** [maxogden/dependency-check#70]
This project could use a change log, particularly since the latest release broke my test suite :-)

See http://keepachangelog.com

No rush, and thanks for maintaining dependency-check <3

**Comment by blakeembrey** [comment]
How about https://github.com/maxogden/dependency-check/releases? I was sticking with the existing style (no change log) but I can start adding them.

**Comment by strugee** [comment]
@blakeembrey that seems okay, with the caveats that a) people can't send PRs to improve the change log and b) people often think to look for a `CHANGELOG.md` file in-repo, but not to look at Releases. Not much to be done for the former, but for the latter I've suggested in other projects adding a `CHANGELOG.md` file that just points to GitHub Releases. Happy to send a PR for this if you want.
