### ISSUE TITLE
Regression: Detective function missing for ""

### ISSUE THREAD

**Issue by strugee** [maxogden/dependency-check#71]
Heya!

If I run `./node_modules/.bin/dependency-check package.json test/*.js` (`test/*.js` is included because it's the only directory that isn't referenced directly or indirectly from `package.json`) with `dependency-check@2.9.0` installed in the local `node_modules` I get `Detective function missing for ""`.

Any idea where this is coming from? This didn't happen with 2.8.0.

**Comment by blakeembrey** [comment]
Probably a result of you requiring an extension-less file (hence `missing for ""`). We could make it so missing detective functions fallback on `.js` like node.js does.

**Comment by blakeembrey** [comment]
Fixed with https://github.com/maxogden/dependency-check/releases/tag/v2.9.1.

**Comment by strugee** [comment]
Neat, thanks @blakeembrey! I can confirm that this is fixed. Your guess is also spot-on - all of the executables referenced by our `package.json`'s `bin` field have no extension. Cheers :tada:
