### ISSUE TITLE
[Suggestion] Read flags and ignored packages for config file (rc?)

### ISSUE THREAD

**Issue by charlike** [maxogden/dependency-check#75]
Hi! It's awesome, and maybe most of the users use the default (`--missing`) thing, but i need to check for incidentally not removed deps, e.g. `--unused` flag, but there are tons of devDeps that i should ignore always, so my npm script line would go very long, which isn't good thing.

So i think it would be good to have config file (rc or json or yaml, no matter) to have default actions to take and default ignored files. 

Ideas? Otherwise, okey no problem, i'll create a package for this. :)

 Soon probably may suggest config format.

edit:

```json
{
  "path": "package.json",
  "check": "missing",
  "ignore": "@types/*"
}
```

- Where `check` can also be array. If it is array it will run `--missing` and `--extra`.
- Where `ignore` can be an array or string - both supported by micromatch ( #65 )

**Comment by blakeembrey** [comment]
I don't think this is necessary today, you could just write your script in a separate file or, as you mentioned, create a separate package that reads from a config file. If it comes up more often, I'll be willing to reconsider the use-case. If you want to ignore dev dependencies, that's what the `--no-dev` flag is for too.
