### ISSUE TITLE
Handle ES6 imports?

### ISSUE THREAD

**Issue by mo** [maxogden/dependency-check#77]
I tried running this on my node + react frontend project, and it says:
[require-lint] Extraneous dependencies: react, react-dom, react-router-dom

...even though I definitely use react. I do import it via ES6 imports though.

**Comment by blakeembrey** [comment]
Try using a different `--detective`. The default is documented (https://github.com/maxogden/dependency-check#--detective) and doesn't handle `import`.

**Comment by stevemao** [comment]
Should we support `import and import()` by default since the spec is stable and most environments support it now?

**Comment by blakeembrey** [comment]
Node.js doesn't. You can use the `--detective` option until it's supported in node.js.

**Comment by voxpelli** [comment]
Eventually the default detective might be switched in a future major release and be swapped with one with wider support – so trying out different detectives enables us to pick the best one to possibly move to in the future, when eg. node.js supports imports
