### ISSUE TITLE
Bug with the defaults (--missing)

### ISSUE THREAD

**Issue by charlike** [maxogden/dependency-check#78]
Hi! :hand: 

I just has one repo, the i am testing some things and i have script for `dependency-check .`, and I have few deps which are not used in the code (actually no other is required, just exporting a function). So, it outputs that everything is okey. Probably, but i don't believe it is correct behavior. 

When you don't have any non-builtin deps required, but you have deps in package.json, i think it should throw error that _"Hey! You have some deps (probably list them), but you didn't use them".

Of when you add `--missing --extra --no-dev` it works, but i don't want to add the `--extra` because i'm forced to add `--no-dev` too. But i think for better defaults which make sense - right, it may be rare case, but it may be useful.

**Comment by blakeembrey** [comment]
This is how it works, please read the documentation: https://github.com/maxogden/dependency-check#cli-usage. `--missing` tells you if modules are missing, `--unused` tells you if you have unused modules and `--no-dev` tells you to ignore dev dependencies in the checks. I don't see a description of a bug in your post, so I'm going to close this. If you feel that is incorrect, please try to clarify your intent with a description of the bug.

**Comment by blakeembrey** [comment]
It does seem the docs could use updating though since the behaviour of `--no-dev` was supported with `--missing` since https://github.com/maxogden/dependency-check/pull/55.
