### ISSUE TITLE
Expose ability to read/use node.js version

### ISSUE THREAD

**Issue by blakeembrey** [maxogden/dependency-check#80]
Based on https://github.com/maxogden/dependency-check/pull/79, it'd be helpful to support input of the minimum node.js version for calculating the built ins. This could be expanded with something like https://github.com/maxogden/dependency-check/issues/46 to also check built ins for other environments (e.g. Electron).

**Comment by voxpelli** [comment]
I was leaning more towards https://github.com/juliangruber/builtins/issues/13 and moving towards the built in list of core modules that comes with Node 9.3.0, but your idea makes sense as well I guess.

I wonder how often someone mistakenly uses a too new core module? Adding a new CLI option seems like something many won’t use. Maybe we could base the initial value on the node engine version range one might have specified in package.json? I use that value in eg. https://github.com/voxpelli/node-installed-check

**Comment by voxpelli** [comment]
Lets go with [module.builtinModules](https://nodejs.org/api/modules.html#modules_module_builtinmodules) once we drop support for anything below Node 10

**Comment by voxpelli** [comment]
Fixed in #103
