### ISSUE TITLE
peerDependencies not being used should not cause an error

### ISSUE THREAD

**Issue by markFromMST** [maxogden/dependency-check#81]
By definition peerDependencies may not actually be directly called from code.  Therefore, they should at minimum have a similar flag to --no-dev, such as --no-peer.  However, it would probably make sense to never include them by default.

**Comment by blakeembrey** [comment]
Feel free to submit a PR for `--no-peer`.

**Comment by voxpelli** [comment]
As I was in the code looking into a possible bug anyway, I fixed it for you @markFromMST. Released as `2.10.0`
