### ISSUE TITLE
Preparation for next major release: 3.0.0

### ISSUE THREAD

**Issue by voxpelli** [maxogden/dependency-check#82]
It's very much time to fix #62 so that we can start using the latest versions of our dependencies.

That means we need to release a new major version of this module and that means it's time for possible breaking changes.

So to prepare for such a release: Is there anything else that's breaking in some regard that we think should be in such a release?

Else there's no reason to wait I think.

Ping @blakeembrey

**Comment by blakeembrey** [comment]
I can't think of any other breaking changes needed. Feel free to bump all the deps for the major release.

**Comment by voxpelli** [comment]
I've pushed a a branch with a 3.0.0 version: https://github.com/maxogden/dependency-check/tree/v3.x

I'm going to test it a bit more and think a bit more about whether there's something more that should be done.

News apart from new engine requirements:

* The API now supports returning a `Promise` instead of a callback, but old way is still supported as well
* The `async` module was removed in favor of a refactoring to promises

**Comment by voxpelli** [comment]
Fixed with: https://github.com/maxogden/dependency-check/commit/d0efa7051fcb9880bb931a17a7ebdf2879a62329
