### ISSUE TITLE
Unexpected token (98:8)

### ISSUE THREAD

**Issue by UX-Unicorn** [maxogden/dependency-check#85]
Whenever I try to run it in my project, I just get an unexpected token error.    It worked fine in a different project.  Is there a way to get a more verbose error message?

$ dependency-check package.json --unused
Unexpected token (98:8)

**Comment by voxpelli** [comment]
I agree. Which version of Node.js and of dependency-check?

**Comment by UX-Unicorn** [comment]
Thank you for the quick response.

$ node -v
v6.9.4

$ npm ls dependency-check -g
D:\Users\nrabbitt\AppData\Roaming\npm
`-- dependency-check@3.0.0

**Comment by voxpelli** [comment]
@UX-Unicorn Sorry for not getting back to you – did this issue get a resolution or are you still having problems? I'm closing, but just mention me if you have new details and I'll open it up again.

Also, try the latest version and see if that would solve your problem.

**Comment by fatso83** [comment]
This is so weird. I am getting this on our CI server and not on our local machines. We have tried switching node versions, upgrading npm, removing node_modules, reinstall all packages, etc.

I would also like to find some way of seeing more debug output. All I get is `Unexpected token (127:7)`. Setting `DEBUG=*` doesn't really help either: 
```
  dependency-check require("react") is a dependency +0ms
  dependency-check require("tcomb") is a dependency +0ms
  dependency-check require("tcomb-react") is a dependency +0ms
  dependency-check require("../lib/i18n") is relative +0ms
  dependency-check require("../lib/service/StyleGuideService") is relative +0ms
  dependency-check require("../types/domain-types") is relative +0ms
  dependency-check require("../types/react-specific-types") is relative +0ms
  dependency-check require("./EncounterLocationTile") is relative +0ms
  dependency-check require("./EncounterStatusText") is relative +0ms
  dependency-check require("./Link") is relative +0ms
Unexpected token (127:7)

```

**Comment by fatso83** [comment]
OK, so I modified `babylon/lib/index.js` in the same way printed the output to get what line 127 looked like:

```javascript
  1     return (
127       <>
  1         {tabId === TabNames.vitals && <EncounterSummary encounterId={encounterId} />}
  2         {tabId === TabNames.criticalinfo && (
  3           <EncounterCriticalInformation encounterId={encounterId} highlightedItemId={highlightedItemId} />
  4         )}
  5         {tabId === TabNames.notes && <EncounterNotesForms encounterId={encounterId} />}
  6         {tabId === TabNames.diagnostics && (
  7           <StartClinicalObservationButton label={_('encounter-tabs.add-new-examination')} />
  8         )}
  9         {tabId === TabNames.gallery && <EncounterImages encounterId={encounterId} />}
 10       </>
 11     );
 12   };
 13 
```

See the line starting with 127, it contains `<>`, which is apparantly not recognized. Why the babel version on our server doesn't recognize this, while our local does, is a bit of a mystery. 

In any case, both Babylon and this project should output the output that breaks it.

**Comment by fatso83** [comment]
I fixed this by doing `npm i detective-es6@latest -D`, seeing that the old `1.2` version used `babelon` instead of `@babel/parse`, needed for the new fragment syntax.

I also understood why it failed on our CI server, as it failed on a new pull request containing a new syntax, which I had not on my local machine.
