### ISSUE TITLE
Unable to detect `ws` in use

### ISSUE THREAD

**Issue by unional** [maxogden/dependency-check#86]
Maybe TypeScript 2.7 related.

`dependency-check` fail saying the package `ws` is not in use:

https://travis-ci.org/unional/komondor-plugin-ws/jobs/340787993
```sh
> dependency-check . --unused --no-dev && dependency-check . --missing --no-dev
Fail! Modules in package.json not used in code: ws, ws
```

But it is used in all code, including `index.ts`:

https://github.com/unional/komondor-plugin-ws/blob/dc/src/index.ts#L2
```ts
// src/index.ts
import WebSocket from 'ws'
```

**Comment by voxpelli** [comment]
See https://github.com/maxogden/dependency-check/issues/59#issuecomment-275934967 – have you specified a custom `detective` that supports TypeScript? And if so: Which one?

**Comment by blakeembrey** [comment]
I’m on mobile so didn’t fully confirm, but it doesn’t look like that import is used by the runtime. Recall that TypeScript will Elise any unused imports in the emitted JS.

**Comment by blakeembrey** [comment]
* elide (sorry, no edit on mobile either)

**Comment by unional** [comment]
Ah yes. It actually didn't use it.
I didn't realize this until now! 😊
