### ISSUE TITLE
2.x currently breaks on Node.js 0.10 and 0.12

### ISSUE THREAD

**Issue by watson** [maxogden/dependency-check#88]
See npm/hosted-git-info#31 for details

**Comment by voxpelli** [comment]
PR towards `5bf9ba65b1482e5de55faef6260637974d9b6c00` is welcome and we can create a `2.x` branch and release a patch that locks down the version

**Comment by voxpelli** [comment]
Right, and `read-package-json` is already pinned down to an old version that was expected to support those versions still 😞 

Seems like `read-package-json` `1.x` is okay, at least when looking at this specific dependency, so if we revert to the version of it that was used in https://github.com/maxogden/dependency-check/commit/15b63695dc062fe96d929b0a751c276704814199 then it should fix at least this issue

**Comment by watson** [comment]
I just did a quick test downgrading to `read-package-json@1.3.3` and it fixed the problem in my case

**Comment by watson** [comment]
Should I make a PR or are you already on it?

**Comment by voxpelli** [comment]
@watson A PR would be great 👍

**Comment by watson** [comment]
Oh, don't I need someone with access to create a 2.x branch first?

**Comment by voxpelli** [comment]
Right, that’s probably, I’ll try to take a look at it tomorrow

**Comment by voxpelli** [comment]
@watson Published `2.10.1` with your fix 👍

**Comment by watson** [comment]
Thnx 👍
