### ISSUE TITLE
dependency-check unsupported on FreeBSD?

### ISSUE THREAD

**Issue by duncan-bayne** [maxogden/dependency-check#89]
I'm creating a [port](https://gitlab.com/duncan-bayne/freebsd-ports-cypress) of [Cypress](https://www.cypress.io/) for FreeBSD.

Currently, `npm install` is failing with the following error:

```
[cli:build        ] Found /usr/home/duncan/code/freebsd-ports-cypress/work/cypress-HEAD/node_modules/.bin/deps-ok
[cli:build        ] /usr/home/duncan/code/freebsd-ports-cypress/work/cypress-HEAD/cli/node_modules/dependency-check/index.js:139
[cli:build        ]   var mainPath = path.resolve(pkg.main || path.join(path.dirname(pkgPath), 'index.js'))
[cli:build        ]                                   ^
[cli:build        ]
[cli:build        ] TypeError: Cannot read property 'main' of undefined
[cli:build        ]     at parse (/usr/home/duncan/code/freebsd-ports-cypress/work/cypress-HEAD/cli/node_modules/dependency-check/index.js:139:35)
[cli:build        ]     at /usr/home/duncan/code/freebsd-ports-cypress/work/cypress-HEAD/cli/node_modules/dependency-check/index.js:27:5
[cli:build        ]     at parseJson (/usr/home/duncan/code/freebsd-ports-cypress/work/cypress-HEAD/cli/node_modules/read-package-json/read-json.js:68:20)
[cli:build        ]     at /usr/home/duncan/code/freebsd-ports-cypress/work/cypress-HEAD/cli/node_modules/read-package-json/read-json.js:48:5
[cli:build        ]     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
[cli:build        ] npm ERR! code ELIFECYCLE
```

I assume this means that `opts.package` on `index.js:132` is undefined.  This works on other platforms (OSX, Linux), so I'm _suspecting_ a problem with dependency-check.

My next port (heh) of call was to see if `dependency-check` tests pass on FreeBSD.  Unfortunately they don't:

```
$ git clone https://github.com/maxogden/dependency-check
Cloning into 'dependency-check'...
remote: Counting objects: 434, done.
remote: Total 434 (delta 0), reused 0 (delta 0), pack-reused 434
Receiving objects: 100% (434/434), 76.84 KiB | 318.00 KiB/s, done.
Resolving deltas: 100% (238/238), done.
$ cd dependency-check
$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN You are using a pre-release version of node and things may not work as expected

added 228 packages from 177 contributors and audited 428 packages in 5.989s
found 0 vulnerabilities
$ dependency-check git:(master) npm test

> dependency-check@3.1.0 test /usr/home/duncan/code/dependency-check
> standard && node cli.js test/ && node cli.js . && node cli.js . --missing --extra --no-dev -e js:detective-cjs

Failed to parse json
Unexpected token � in JSON at position 0 while parsing near '�Us.��q...'
npm ERR! Test failed.  See above for more details.
```

I'm happy to help fix this, as it's currently blocking my attempts to port Cypress.  But I was wondering (a) whether this is a known problem, and (b) if you have any suggestions on how to proceed?

Versions of things:

* Node v10.4.2-pre
* NPM 6.1.0
* FreeBSD 11.1-RELEASE GENERIC amd64

**Comment by maxogden** [comment]
hi, I wouldn't recommend running this as a post install script in general,
so you can probably just remove this as a dependency for the purposes of
your porting

**Comment by duncan-bayne** [comment]
@maxogden Thanks for the prompt response!  This isn't post-installation though, this is _during_ the compilation step.  In the port's Makefile:

```
# Assume we're using a manually installed pre-release version of Node
# here, which is necessary until the latest Node drops into Ports.
do-build:
		@(cd ${WRKSRC} ; npm --nodedir=/usr/src/node install )

.include <bsd.port.mk>
```

`dependency-check` is being invoked by the Cypress build process here, during pre-build:

```
  "scripts": {
    "test": "npm run test-unit",
    "test-unit": "npm run dtslint && npm run unit",
    "test-watch": "npm run unit -- --watch",
    "test-dependencies": "bin-up deps-ok && dependency-check . --no-dev",
    "test-debug": "node --inspect --debug-brk $(bin-up _mocha)",
    "test-cov": "nyc npm run unit",
    "unit": "BLUEBIRD_DEBUG=1 NODE_ENV=test bin-up mocha --reporter mocha-multi-reporters --reporter-options configFile=../mocha-reporter-config.json",
    "lint": "bin-up eslint --fix *.js bin/* lib/*.js lib/**/*.js test/*.js test/**/*.js",
    "dtslint": "dtslint types",
    "prebuild": "npm run test-dependencies && node ./scripts/start-build.js",
    "build": "node ./scripts/build.js",
    "prerelease": "npm run build",
    "release": "cd build && releaser --no-node --no-changelog",
    "size": "t=\"$(npm pack .)\"; wc -c \"${t}\"; tar tvf \"${t}\"; rm \"${t}\";"
  },
```

**Comment by maxogden** [comment]
hmm that also seems like incorrect behavior. the idea of this module is to catch things before you publish, not when you install. i would just remove it in your port

**Comment by duncan-bayne** [comment]
Oh, okay.  I might raise an upstream PR to move this, then, as it sounds like the problem lies with Cypress.

If I understand you correctly, the fix would be to move `test-dependencies` into the `release` script above?  (Which is also _not_ called by the port :) ).

**Comment by voxpelli** [comment]
Correct 🙂

And If there’s an issue with this module when developing on FreeBSD - then it would be great to have another issue opened for that - then we can test and ensure that it works 👍 (I wonder if there’s any CI similar to Travis that supports FreeBSD?)

**Comment by duncan-bayne** [comment]
@voxpelli I've opened an upstream (relative to my port) issue on cypress, & will re-open an issue here specific to the FreeBSD weirdness I'm seeing.

**Comment by duncan-bayne** [comment]
@maxogden @voxpelli I've raised a PR to move the call to `dependency-check` to the release step, but the Cypress folks would prefer it remain where it is, & have asked for clarification of your suggestion.  If it's not too much trouble, could you please drop by https://github.com/cypress-io/cypress/pull/2012#issuecomment-400044059 for discussion?
