### ISSUE TITLE
Allow --ignore-module also for --missing

### ISSUE THREAD

**Issue by Croydon** [maxogden/dependency-check#94]
We are using yarn link to make some modules available for our main yarn package.

dependency-check can't know if this modules are actually there or not and this is fine, but it would be really awesome if we could just ignore these modules with --ignore-module for meaningfull results

**Comment by blakeembrey** [comment]
I believe I merged this feature a couple of years ago with https://github.com/maxogden/dependency-check/commit/72b46c4a77847c08962e58383fe3a68942f6dd40. Let me double check, can you let me know if that's the feature you're requesting?

**Comment by Croydon** [comment]
I'm not absolutely sure if I'm reading this commit correctly, but I think that this is the feature I want.

In this case, however, I'm either using it wrong or it doesn't work, since I already tried to use it.

**Comment by blakeembrey** [comment]
What version are you using? Can you give an example of what you want and what’s not working?

**Comment by Croydon** [comment]
I just had a look again at our script which is calling dependency-check and I pretty much instantly saw our usage error. Not all modules which should be ignored got passed along correctly...

Sorry, for the noise and thanks for your work!

**Comment by Croydon** [comment]
As a side note. Maybe the readme should get a small update to make it more clear, that --ignore-module is indeed working for --missing as well. 

The parameter explanation there might give the impression that it only works for --unused

**Comment by blakeembrey** [comment]
@Croydon Would love to accept a PR with any clarification you'd like to provide! 👍
