### ISSUE TITLE
Glob ignore

### ISSUE THREAD

**Issue by bcomnes** [maxogden/dependency-check#96]
This supports globing for entry-points, but it would be great if we could glob ignore some packages as well.  Some ecosystems have the concept of plugins which are side-loaded and it would be nice to `-i @namespace/foo-*`

**Comment by blakeembrey** [comment]
See https://github.com/maxogden/dependency-check/issues/65.

**Comment by bcomnes** [comment]
It’s a dupe!  Ty

**Comment by blakeembrey** [comment]
Happy to accept a PR though!

**Comment by bcomnes** [comment]
When things calm down on my current project, I have a number of upstream contributions I would like to make, including this possibly.
